# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb import qqbot_pb2 as qqbot__pb2


class QQBotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMsg = channel.unary_unary(
                '/proto.QQBotService/SendMsg',
                request_serializer=qqbot__pb2.SendMsgReq.SerializeToString,
                response_deserializer=qqbot__pb2.Resp.FromString,
                )
        self.Self = channel.unary_unary(
                '/proto.QQBotService/Self',
                request_serializer=qqbot__pb2.Empty.SerializeToString,
                response_deserializer=qqbot__pb2.Resp.FromString,
                )
        self.Friends = channel.unary_unary(
                '/proto.QQBotService/Friends',
                request_serializer=qqbot__pb2.Empty.SerializeToString,
                response_deserializer=qqbot__pb2.Resp.FromString,
                )
        self.Groups = channel.unary_unary(
                '/proto.QQBotService/Groups',
                request_serializer=qqbot__pb2.Empty.SerializeToString,
                response_deserializer=qqbot__pb2.Resp.FromString,
                )


class QQBotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Self(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Friends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Groups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QQBotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMsg,
                    request_deserializer=qqbot__pb2.SendMsgReq.FromString,
                    response_serializer=qqbot__pb2.Resp.SerializeToString,
            ),
            'Self': grpc.unary_unary_rpc_method_handler(
                    servicer.Self,
                    request_deserializer=qqbot__pb2.Empty.FromString,
                    response_serializer=qqbot__pb2.Resp.SerializeToString,
            ),
            'Friends': grpc.unary_unary_rpc_method_handler(
                    servicer.Friends,
                    request_deserializer=qqbot__pb2.Empty.FromString,
                    response_serializer=qqbot__pb2.Resp.SerializeToString,
            ),
            'Groups': grpc.unary_unary_rpc_method_handler(
                    servicer.Groups,
                    request_deserializer=qqbot__pb2.Empty.FromString,
                    response_serializer=qqbot__pb2.Resp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.QQBotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QQBotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QQBotService/SendMsg',
            qqbot__pb2.SendMsgReq.SerializeToString,
            qqbot__pb2.Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Self(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QQBotService/Self',
            qqbot__pb2.Empty.SerializeToString,
            qqbot__pb2.Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Friends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QQBotService/Friends',
            qqbot__pb2.Empty.SerializeToString,
            qqbot__pb2.Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Groups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QQBotService/Groups',
            qqbot__pb2.Empty.SerializeToString,
            qqbot__pb2.Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
