# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qqbot.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqqbot.proto\x12\x05proto\"\x07\n\x05\x45mpty\":\n\nSendMsgReq\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04\x63hat\x18\x02 \x01(\x03\x12\r\n\x05group\x18\x03 \x01(\x08\"\x96\x01\n\x04User\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\x12\x0e\n\x06remark\x18\x08 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\x03\x12\x10\n\x08\x63\x61rdName\x18\x04 \x01(\t\x12\x10\n\x08joinTime\x18\x05 \x01(\x03\x12\x15\n\rlastSpeakTime\x18\x06 \x01(\x03\x12\x14\n\x0cspecialTitle\x18\x07 \x01(\t\"\xaa\x01\n\x05Group\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\x03\x12\x17\n\x0fgroupCreateTime\x18\x04 \x01(\r\x12\x12\n\nGroupLevel\x18\x05 \x01(\r\x12\x13\n\x0bMemberCount\x18\x06 \x01(\x04\x12\x16\n\x0eMaxMemberCount\x18\x07 \x01(\x04\x12\x1c\n\x07members\x18\x08 \x03(\x0b\x32\x0b.proto.User\"n\n\x04Resp\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x04self\x18\x02 \x01(\x0b\x32\x0b.proto.User\x12\x1c\n\x07\x66riends\x18\x03 \x03(\x0b\x32\x0b.proto.User\x12\x1c\n\x06groups\x18\x04 \x03(\x0b\x32\x0c.proto.Group2\xaf\x01\n\x0cQQBotService\x12+\n\x07SendMsg\x12\x11.proto.SendMsgReq\x1a\x0b.proto.Resp\"\x00\x12#\n\x04Self\x12\x0c.proto.Empty\x1a\x0b.proto.Resp\"\x00\x12&\n\x07\x46riends\x12\x0c.proto.Empty\x1a\x0b.proto.Resp\"\x00\x12%\n\x06Groups\x12\x0c.proto.Empty\x1a\x0b.proto.Resp\"\x00\x42\x14Z\x12qqbot_pb/;qqbot_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qqbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022qqbot_pb/;qqbot_pb'
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_SENDMSGREQ']._serialized_start=31
  _globals['_SENDMSGREQ']._serialized_end=89
  _globals['_USER']._serialized_start=92
  _globals['_USER']._serialized_end=242
  _globals['_GROUP']._serialized_start=245
  _globals['_GROUP']._serialized_end=415
  _globals['_RESP']._serialized_start=417
  _globals['_RESP']._serialized_end=527
  _globals['_QQBOTSERVICE']._serialized_start=530
  _globals['_QQBOTSERVICE']._serialized_end=705
# @@protoc_insertion_point(module_scope)
